### ISSUE TITLE
Undefined property: stdClass::$language

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/comment_notify#1]
I've got dozens of these messages in my site logs:

> Notice: Undefined property: stdClass::$language in comment_notify_tokens() (line 36 of /[SNIP]/modules/comment_notify/comment_notify.tokens.inc).

**Comment by herbdool** [comment]
Thanks @BWPanda. I think this https://github.com/backdrop-contrib/comment_notify/commit/338246e5ee5b103fa1788a0d2bf1206646ec32cf fixes it.

**Comment by ghost** [comment]
Awesome!
