### ISSUE TITLE
Problem with Show comment replies in a threaded list 

### ISSUE THREAD

**Issue by Acertijo** [backdrop-contrib/comment_notify#2]
Hi, when install the Comment Notify module, it shows all comments without parents even with the option "Show comment replies in a threaded list" enabled

you can see the example here: https://i.ibb.co/mbmt9xt/test.jpg

**Comment by herbdool** [comment]
I believe that option is part of the core comment module and not this module. You might see the same option even if you disable this module.

**Comment by herbdool** [comment]
You can search for a similar issue here https://github.com/backdrop/backdrop-issues/issues or add yours if it doesn't already exist.
