### ISSUE TITLE
[] operator not supported for strings error

### ISSUE THREAD

**Issue by sbgraphicdesign** [backdrop-contrib/comment_notify#3]
I was getting this error on my MAMP install (php 7.2.21). I believe this is an issue with [] in php 7.1 and above:

Error: [] operator not supported for strings in comment_notify_settings() (line 591 of .../modules/comment_notify/comment_notify.module)

Here's line 591:
`$anonymous_problems[] = l(t('@content-type', array('@content-type' => $name)), 'admin/structure/types/manage/' . $type);`

I added one extra line of code above and everything seems to be working again
`$anonymous_problems = array();`

**Comment by herbdool** [comment]
Thanks for reporting the bug. I've added a fix and will make a new release.
